DROP TABLE IF EXISTS ItemColor CASCADE;
DROP TABLE IF EXISTS ItemPhoto CASCADE;
DROP TABLE IF EXISTS CollectionColor CASCADE;
DROP TABLE IF EXISTS CollectionPhoto CASCADE;

DROP TABLE IF EXISTS ItemTranslation CASCADE;
DROP TABLE IF EXISTS CollectionTranslation CASCADE;
DROP TABLE IF EXISTS CategoryTranslation CASCADE;

DROP TABLE IF EXISTS Item CASCADE;
DROP TABLE IF EXISTS Collection CASCADE;
DROP TABLE IF EXISTS Category CASCADE;
DROP TABLE IF EXISTS Color CASCADE;
DROP TABLE IF EXISTS Photo CASCADE;

DROP TABLE IF EXISTS Language CASCADE;
